server:
  port: 8888
spring:
  application:
    name: simcomex-config-server
  cloud:
    config:
      server:
        git:
          uri: git@gitlab.sefa.pa.gov.br:sefa/simcomex-microsservicos/simcomex-config-server
          default-label: master
          search-paths: 'simcomex*'